apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: nginx-subscription-blue-3
  namespace: nginx-blue
  labels:
    app: nginx-deployment
spec:
  channel: mortgage-ch/mortgage-channel
  placement:
    placementRef:
      name: nginx-deployment
      kind: PlacementRule
