apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: mortgagerc-placement
  labels:
    app: mortgagerc
spec:
  clusterReplicas: 1
  clusterLabels:
    matchLabels:
      environment: Dev

