apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: mortgagers-placement
  labels:
    app: mortgagers
spec:
  clusterReplicas: 1
  clusterLabels:
    matchLabels:
      environment: Dev
