apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-commit: 9f1ceb2a37afd1ee5810b341bdda2ea948e77ed1
    apps.open-cluster-management.io/github-branch: master
    apps.open-cluster-management.io/github-path: placement/nginx
  labels:
    app: nginx-app
  name: placement-nginx-subscription
  namespace: nginx-app-ns
spec:
  channel: gitops-chn-ns/gitops
  placement:
    placementRef:
      kind: PlacementRule
      name: nginx-placement
