apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: mortgagedc-placement
  labels:
    app: mortgagedc
spec:
  clusterReplicas: 1
  clusterLabels:
    matchLabels:
      environment: Dev
