apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: mortgagepod-placement
  labels:
    app: mortgagepod
spec:
  clusterReplicas: 1
  clusterLabels:
    matchLabels:
      environment: Dev

