apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: guestbook-app
  namespace: default
  labels:
    app: guestbook-app
spec:
  channel: gbapp-ch/guestbook-app-latest
  packageFilter:
    filterRef:
      name: resource-filter-configmap
  placement:
    placementRef:
      name: dev-clusters
      kind: PlacementRule
