apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: dev-clusters
  namespace: app-guestbook-git-ns
spec:
  clusterLabels:
    matchLabels:
      environment: Dev
  clusterReplicas: 4
